---
name: dbt
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<23
  - wheel
  - python>=3.10,<3.11
  - pip:
      - dbt-duckdb>=1.5.2
      - duckdb==0.7.0
